server:
  port: 12000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jiangchuan666/config-center.git
  application:
    name: config
  rabbitmq:
    host: 192.168.48.133

management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh