<%@ page import="java.util.Map" %>
<%@ page import="com.jc.usercase.entity.User" %>
<%@ page import="org.apache.commons.beanutils.BeanUtils" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%
    //访问权限控制
    if (request.getSession().getAttribute("userInfo") == null) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }
    //对于有些页面，应该设置禁止直接访问，必须来源内部链接跳转
    String referer = request.getHeader("referer");
    if (referer == null || "".equals(referer) || !referer.contains(request.getContextPath())) {
        response.sendRedirect(request.getContextPath() + "/fuzzyQueryServlet");
        return;
    }

    //获取请求参数,并封装参数
    Map<String, String[]> parameterMap = request.getParameterMap();
    User user = new User();
    BeanUtils.populate(user, parameterMap);
    //将参数放置在域对象中
    pageContext.setAttribute("user", user);

%>
<!DOCTYPE html>
<!-- 网页使用的语言 -->
<html lang="zh-CN">
<head>
    <%--    <base href="<%=basePath%>"/>--%>
    <!-- 指定字符集 -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>修改用户</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <script src="js/jquery-2.1.0.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

</head>
<body>
<div class="container" style="width: 400px;">
    <h3 style="text-align: center;">修改联系人</h3>
    <form action="${pageContext.request.contextPath}/updateUserServlet" method="post">
        <div class="form-group">
            <input type="hidden" name="id" value="${user.id}"/>
        </div>
        <div class="form-group">
            <label for="realName">姓名：</label>
            <input type="text" class="form-control" id="realName" name="realName" readonly="readonly" placeholder="请输入姓名"
                   value="${user.realName}"/>
        </div>

        <div class="form-group">
            <label>性别：</label>
            <c:if com.jc.test="${'男'.equals(user.sex)}">
                <input type="radio" name="sex" value="男" checked/>男
                <input type="radio" name="sex" value="女"/>女
            </c:if>
            <c:if com.jc.test="${'女'.equals(user.sex)}">
                <input type="radio" name="sex" value="男"/>男
                <input type="radio" name="sex" value="女" checked/>女
            </c:if>
        </div>

        <div class="form-group">
            <label for="age">年龄：</label>
            <input type="text" class="form-control" id="age" name="age" placeholder="请输入年龄" value="${user.age}"/>
        </div>

        <div class="form-group">
            <label for="address">籍贯：</label>
            <select name="address" id="address" class="form-control">
                <c:choose>
                    <c:when com.jc.test="${'陕西'.equals(user.address)}">
                        <option value="陕西" selected>陕西</option>
                        <option value="北京">北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津">天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南">河南</option>
                        <option value="湖北">湖北</option>
                        <option value="湖南">湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'北京'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" selected>北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津">天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南">河南</option>
                        <option value="湖北">湖北</option>
                        <option value="湖南">湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'上海'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海" selected>上海</option>
                        <option value="山西">山西</option>
                        <option value="天津">天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南">河南</option>
                        <option value="湖北">湖北</option>
                        <option value="湖南">湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'山西'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西" selected>山西</option>
                        <option value="天津">天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南">河南</option>
                        <option value="湖北">湖北</option>
                        <option value="湖南">湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'天津'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" selected>天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南">河南</option>
                        <option value="湖北">湖北</option>
                        <option value="湖南">湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'河北'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" selected>河北</option>
                        <option value="河南">河南</option>
                        <option value="湖北">湖北</option>
                        <option value="湖南">湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'河南'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" selected>河南</option>
                        <option value="湖北">湖北</option>
                        <option value="湖南">湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'湖北'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" selected>湖北</option>
                        <option value="湖南">湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'湖南'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" selected>湖南</option>
                        <option value="黑龙江">黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'黑龙江'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" selected>黑龙江</option>
                        <option value="吉林">吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'吉林'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" selected>吉林</option>
                        <option value="辽宁">辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'辽宁'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" selected>辽宁</option>
                        <option value="青海">青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'青海'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" selected>青海</option>
                        <option value="西藏">西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'西藏'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" selected>西藏</option>
                        <option value="四川">四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'四川'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" selected>四川</option>
                        <option value="重庆">重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'重庆'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" selected>重庆</option>
                        <option value="宁夏">宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'宁夏'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" selected>宁夏</option>
                        <option value="甘肃">甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'甘肃'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" selected>甘肃</option>
                        <option value="新疆">新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'新疆'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" selected>新疆</option>
                        <option value="内蒙古">内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'内蒙古'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" selected>内蒙古</option>
                        <option value="江苏">江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'江苏'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" selected>江苏</option>
                        <option value="浙江">浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'浙江'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" selected>浙江</option>
                        <option value="海南">海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'海南'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" selected>海南</option>
                        <option value="福建">福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'福建'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" selected>福建</option>
                        <option value="广东">广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'广东'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" selected>广东</option>
                        <option value="广西">广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'广西'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" selected>广西</option>
                        <option value="贵州">贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'贵州'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" >广西</option>
                        <option value="贵州" selected>贵州</option>
                        <option value="云南">云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'云南'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" >广西</option>
                        <option value="贵州" >贵州</option>
                        <option value="云南" selected>云南</option>
                        <option value="江西">江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'江西'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" >广西</option>
                        <option value="贵州" >贵州</option>
                        <option value="云南" >云南</option>
                        <option value="江西" selected>江西</option>
                        <option value="安徽">安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'安徽'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" >广西</option>
                        <option value="贵州" >贵州</option>
                        <option value="云南" >云南</option>
                        <option value="江西" >江西</option>
                        <option value="安徽" selected>安徽</option>
                        <option value="山东">山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'山东'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" >广西</option>
                        <option value="贵州" >贵州</option>
                        <option value="云南" >云南</option>
                        <option value="江西" >江西</option>
                        <option value="安徽" >安徽</option>
                        <option value="山东" selected>山东</option>
                        <option value="香港">香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'香港'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" >广西</option>
                        <option value="贵州" >贵州</option>
                        <option value="云南" >云南</option>
                        <option value="江西" >江西</option>
                        <option value="安徽" >安徽</option>
                        <option value="山东" >山东</option>
                        <option value="香港" selected>香港</option>
                        <option value="澳门">澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'澳门'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" >广西</option>
                        <option value="贵州" >贵州</option>
                        <option value="云南" >云南</option>
                        <option value="江西" >江西</option>
                        <option value="安徽" >安徽</option>
                        <option value="山东" >山东</option>
                        <option value="香港" >香港</option>
                        <option value="澳门" selected>澳门</option>
                        <option value="台湾">台湾</option>
                    </c:when>
                    <c:when com.jc.test="${'台湾'.equals(user.address)}">
                        <option value="陕西" >陕西</option>
                        <option value="北京" >北京</option>
                        <option value="上海">上海</option>
                        <option value="山西">山西</option>
                        <option value="天津" >天津</option>
                        <option value="河北" >河北</option>
                        <option value="河南" >河南</option>
                        <option value="湖北" >湖北</option>
                        <option value="湖南" >湖南</option>
                        <option value="黑龙江" >黑龙江</option>
                        <option value="吉林" >吉林</option>
                        <option value="辽宁" >辽宁</option>
                        <option value="青海" >青海</option>
                        <option value="西藏" >西藏</option>
                        <option value="四川" >四川</option>
                        <option value="重庆" >重庆</option>
                        <option value="宁夏" >宁夏</option>
                        <option value="甘肃" >甘肃</option>
                        <option value="新疆" >新疆</option>
                        <option value="内蒙古" >内蒙古</option>
                        <option value="江苏" >江苏</option>
                        <option value="浙江" >浙江</option>
                        <option value="海南" >海南</option>
                        <option value="福建" >福建</option>
                        <option value="广东" >广东</option>
                        <option value="广西" >广西</option>
                        <option value="贵州" >贵州</option>
                        <option value="云南" >云南</option>
                        <option value="江西" >江西</option>
                        <option value="安徽" >安徽</option>
                        <option value="山东" >山东</option>
                        <option value="香港" >香港</option>
                        <option value="澳门" >澳门</option>
                        <option value="台湾" selected>台湾</option>
                    </c:when>
                </c:choose>

            </select>
        </div>

        <div class="form-group">
            <label for="qq">QQ：</label>
            <input type="text" id="qq" class="form-control" name="qq" placeholder="请输入QQ号码" value="${user.qq}"/>
        </div>

        <div class="form-group">
            <label for="email">Email：</label>
            <input type="text" id="email" class="form-control" name="email" placeholder="请输入邮箱地址"
                   value="${user.email}"/>
        </div>

        <div class="form-group" style="text-align: center">
            <input id="submit" class="btn btn-primary" type="submit" value="提交"/>
            <input class="btn btn-default" type="reset" value="重置"/>
            <input class="btn btn-default" type="button" value="返回"
                   onclick="location.href='${pageContext.request.contextPath}/fuzzyQueryServlet'"/>
        </div>
    </form>
</div>
<script>
    <%--//设置select选中状态--%>
    <%--let el = document.getElementsByTagName("option");--%>
    <%--for (let i = 0; i < el.length; i++) {--%>
    <%--    let innerText = el[i].innerText;--%>
    <%--    // document.write(innerText+'---'+el[i].selected +'<br>')--%>
    <%--    if (${user.address==innerText}) {--%>
    <%--        el[i].selected = 'selected';--%>
    <%--        break;--%>
    <%--    }--%>
    <%--}--%>

    //提交表单
    document.getElementById("submit").onclick=function () {
        let age = document.getElementById("age");
        let qq = document.getElementById("qq");
        let email = document.getElementById("email");
        if (age.value && qq.value && email.value) {
            //校验通过
            return true;
        }
        alert("请将用户信息填写完整");
        return false;
    };
</script>
</body>
</html>